---
resources:
  - name: git-repository
    type: git
    source:
      uri: "https://github.com/rudolfsonjunior/test-app.git"

jobs:
- name: commit-stage
  plan:
  - get: git-repository
    trigger: true
  - task: run-tests
    config:
      platform: linux

      inputs:
      - name: git-repository

      image_resource:
        type: docker-image
        source: { repository: ruby, tag: 2.3.0 }

      run:
        path: sh
        dir: git-repository
        args:
          - -exc
          - |
            bundle install
            rspec
            brakeman -z

- name: deploy-stage
  serial: true
  plan:
  - get: git-repository
    trigger: true
    passed: [commit-stage]
  - task: deploy-heroku
    params:
      HEROKU_EMAIL: {{heroku_email}}
      HEROKU_TOKEN: {{heroku_token}}
    config:
      platform: linux

      image_resource:
        type: docker-image
        source: { repository: concourse/bosh-cli }

      inputs:
        - name: git-repository

      run:
        path: sh
        dir: git-repository
        args:
          - -exc
          - |
            cat > ~/.netrc <<EOF
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_TOKEN
            EOF
            git push https://git.heroku.com/fhs-test-app.git master:refs/heads/master
